### ISSUE TITLE
data_types.log ?

### ISSUE THREAD

**Issue by Serpens66** [OldEnt/crusader-kings-3-triggers-modifiers-effects-event-scopes-targets-on-actions-code-revisions-list#2]
Thank you very much for this, it contains a useful small documentation, especially regarding triggers and effects.

In case the purpose of this repository is this, then I think you should also include other log file, like "data_types.log".
If I understand this log correctly, all capitalized commands in there are for GUI/localization only. And the non capitalized are for scope access in txt scripts, eg. "dynasty" can be used to access the dynasty of the current scope.

**Comment by OldEnt** [comment]
I don't mod CK3 but if those are useful I'll look into this. Sorry, I have only just noticed your post.

**Comment by OldEnt** [comment]
Added data_types.log in [f1824ed](https://github.com/OldEnt/crusader-kings-3-triggers-modifiers-effects-event-scopes-targets-on-actions-code-revisions-list/commit/f1824ed42d1f71adbe5a782080e0db60bbb14444). Maybe one day I will edit previous commits to include data types for pre-1.5 versions.
